#!/bin/sh

set -e

PREREQ="cryptroot"

prereqs()
{
    echo "$PREREQ"
}

case $1 in
    prereqs)
	    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

MULTIARCH=`dpkg-architecture -qDEB_HOST_MULTIARCH`

copy_exec /bin/bash
copy_exec /usr/bin/ykchalresp
copy_exec /usr/bin/ykinfo
copy_exec /usr/bin/sha256sum
copy_exec /usr/bin/tpm2_selftest
copy_exec /usr/bin/tpm2_load
copy_exec /usr/bin/tpm2_encryptdecrypt
copy_exec /usr/bin/tpm2_createprimary
copy_exec /usr/lib/${MULTIARCH}/libtss2-tcti-device.so.0
mkdir -p "${DESTDIR}/usr/lib/cryptsetup"
mkdir -p "${DESTDIR}/etc/cryptsetup"
cp -r /usr/lib/cryptsetup/2fa "${DESTDIR}/usr/lib/cryptsetup"
cp -r /etc/cryptsetup/2fa "${DESTDIR}/etc/cryptsetup"

exit 0
